create table if not exists registration_db.usr(
    id integer not null unique generated by default as identity primary key ,
    created_date timestamp not null default current_timestamp,
    updated_date timestamp not null default current_timestamp ,
    username varchar(50) not null unique ,
    full_name varchar(70) not null ,
    password varchar(800) not null ,
    email varchar(50) not null unique ,
    phone varchar(15) not null unique ,
    age integer not null ,
    user_state varchar(20) not null
)