create table if not exists registration_db.role (
    id integer not null unique generated by default as identity primary key ,
    created_date timestamp not null default current_timestamp ,
    updated_date timestamp not null default current_timestamp ,
    roles varchar(50) not null unique
)