create table if not exists registration_db.user_token (
    id integer not null unique generated by default as identity primary key ,
    user_id integer not null references registration_db.usr ,
    created_date timestamp not null default current_timestamp ,
    updated_date timestamp not null default current_timestamp ,
    expire_date timestamp not null ,
    token varchar(800) not null unique ,
    token_purpose varchar(50) not null ,
    token_state varchar(50) not null
)